language: shell

services:
  - docker

os: linux

dist: bionic

git:
  depth: 1

notifications:
  email: false

env:
  matrix:
    - PYTHON_VER=python=3.8 CYTHON_VER=cython NUMPY_VER=numpy SCIPY_VER=scipy SKLEARN_VER=scikit-learn==0.22
    - PYTHON_VER=python=3.8 CYTHON_VER=cython NUMPY_VER=numpy SCIPY_VER=scipy SKLEARN_VER=scikit-learn==0.21.1
    - PYTHON_VER=python=3.7 CYTHON_VER=cython NUMPY_VER=numpy SCIPY_VER=scipy SKLEARN_VER=scikit-learn==0.22
    - PYTHON_VER=python=3.7 CYTHON_VER=cython NUMPY_VER=numpy SCIPY_VER=scipy SKLEARN_VER=scikit-learn==0.21
    - PYTHON_VER=python=3.7 CYTHON_VER=cython==0.27.3 NUMPY_VER=numpy SCIPY_VER=scipy SKLEARN_VER=scikit-learn==0.20
    - PYTHON_VER=python=3.6 CYTHON_VER=cython NUMPY_VER=numpy SCIPY_VER=scipy SKLEARN_VER=scikit-learn==0.21
    - PYTHON_VER=python=3.6 CYTHON_VER=cython==0.27.3 NUMPY_VER=numpy SCIPY_VER=scipy SKLEARN_VER=scikit-learn==0.20
    - PYTHON_VER=python=3.6 CYTHON_VER=cython==0.27.3 NUMPY_VER=numpy==1.14.5 SCIPY_VER=scipy==1.1.0 SKLEARN_VER=scikit-learn==0.19
    - PYTHON_VER=python=3.6 CYTHON_VER=cython==0.27.3 NUMPY_VER=numpy==1.9.3 SCIPY_VER=scipy==0.16.0 SKLEARN_VER=scikit-learn==0.18
    - PYTHON_VER=python=3.6 CYTHON_VER=cython==0.27.3 NUMPY_VER=numpy==1.9.3 SCIPY_VER=scipy==0.16.0 SKLEARN_VER=scikit-learn==0.17
    - PYTHON_VER=python=3.5 CYTHON_VER=cython NUMPY_VER=numpy SCIPY_VER=scipy SKLEARN_VER=scikit-learn==0.21
    - PYTHON_VER=python=3.5 CYTHON_VER=cython==0.27.3 NUMPY_VER=numpy SCIPY_VER=scipy SKLEARN_VER=scikit-learn==0.20
    - PYTHON_VER=python=3.5 CYTHON_VER=cython==0.27.3 NUMPY_VER=numpy==1.14.5 SCIPY_VER=scipy==1.1.0 SKLEARN_VER=scikit-learn==0.19
    - PYTHON_VER=python=3.5 CYTHON_VER=cython==0.27.3 NUMPY_VER=numpy==1.9.3 SCIPY_VER=scipy==0.16.0 SKLEARN_VER=scikit-learn==0.18
    - PYTHON_VER=python=3.5 CYTHON_VER=cython==0.27.3 NUMPY_VER=numpy==1.9.3 SCIPY_VER=scipy==0.16.0 SKLEARN_VER=scikit-learn==0.17

before_install:
  - travis_wait 30 docker build
    -t sklearn-porter
    --build-arg PYTHON_VER=${PYTHON_VER}
    --build-arg CYTHON_VER=${CYTHON_VER}
    --build-arg NUMPY_VER=${NUMPY_VER}
    --build-arg SCIPY_VER=${SCIPY_VER}
    --build-arg SKLEARN_VER=${SKLEARN_VER}
    --no-cache .
  - docker run
    --detach
    --entrypoint=/bin/bash
    --name test
    -t sklearn-porter

script:
  - docker exec -it test ./docker-entrypoint.sh
    pytest tests -v
      --cov=sklearn_porter
      --disable-warnings
      --numprocesses=auto
      -p no:doctest
      -o python_files="EstimatorTest.py"
      -o python_functions="test_*"

after_success:
  - test ${PYTHON_VER} = "python=3.7" &&
    test ${CYTHON_VER} = "cython" &&
    test ${NUMPY_VER} = "numpy" &&
    test ${SCIPY_VER} = "scipy" &&
    test ${SKLEARN_VER} = "scikit-learn==0.21" &&
      docker exec -it test ./docker-entrypoint.sh
        codecov
          --token ${CODECOV_TOKEN}
          --name "${TRAVIS_COMMIT}"
          --env ${PYTHON_VER}
                ${CYTHON_VER}
                ${NUMPY_VER}
                ${SCIPY_VER}
                ${SKLEARN_VER}